import { chromium } from 'playwright-core'
process.env.LD_LIBRARY_PATH='/tmp/chromelibs/root/usr/lib/x86_64-linux-gnu:'+(process.env.LD_LIBRARY_PATH||'')
const EXE=process.env.HOME+'/.cache/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-linux64/chrome-headless-shell'
const b=await chromium.launch({executablePath:EXE,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--disable-dev-shm-usage']})
const ctx=await b.newContext({viewport:{width:1600,height:820},deviceScaleFactor:1.25})
const p=await ctx.newPage()
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERR '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('CONSOLE '+m.text())})
const q = process.env.Q || 'capture=1&nofx=1&lsnap=1'
await p.goto('http://127.0.0.1:4173/?'+q,{waitUntil:'load',timeout:60000})
await p.waitForSelector('canvas'); await p.waitForTimeout(2600)
await p.getByRole('button',{name:'Catalog'}).click()
await p.locator('.cat-row',{hasText:'Week 01'}).getByRole('button',{name:'Enter'}).click()
await p.waitForSelector('.study-cinematic',{timeout:5000})
const next=p.getByRole('button',{name:/Next/})
const tag = process.env.TAG || 'rig'
// page 0: two frames to confirm motion (talking, not frozen)
await p.waitForTimeout(1800); await p.screenshot({path:`renders/${tag}_p0a.png`})
await p.waitForTimeout(1600); await p.screenshot({path:`renders/${tag}_p0b.png`}); console.log('p0')
await next.click(); await p.waitForTimeout(1800); await p.screenshot({path:`renders/${tag}_p1a.png`})
await p.waitForTimeout(1600); await p.screenshot({path:`renders/${tag}_p1b.png`}); console.log('p1')
await next.click(); await p.waitForTimeout(2400); await p.screenshot({path:`renders/${tag}_p2.png`}); console.log('p2')
await next.click(); await p.waitForTimeout(2400); await p.screenshot({path:`renders/${tag}_p3.png`}); console.log('p3')
await next.click(); await p.waitForTimeout(2400); await p.screenshot({path:`renders/${tag}_p4.png`}); console.log('p4')
console.log('errors:', errs.slice(0,8))
await b.close()
